### PR TITLE
Removed docs-folder and added npm dev-dependency on yuidocjs

### PR DESCRIPTION
**Pull request by SimonSimCity**
Reopening https://github.com/Meteor-Community-Packages/meteor-roles/pull/272

### CODE REVIEW

**Comment by mitar** [comment]
Should we be building docs and storing them into some special branch? And then have GitHub pages there?

**Comment by SimonSimCity** [comment]
Could well do this - I just don't want to update these generated docs every time I update the code.

**Comment by mitar** [comment]
OK, see https://github.com/Meteor-Community-Packages/meteor-roles/issues/284 for more information.

**Comment by SimonSimCity** [comment]
Would you keep it in this repo? I wouldn't ... and I've also removed the generated docs from the v3 branch I have. If git has something as assets or if we could push those docs to a separate repo, I'd be on it - I just see it at the wrong place in this repo - or at least on this branch - together with the code.

**Comment by SimonSimCity** [comment]
Would be nice to get this set up. Please let me know how I could do this. Until then, I'll at least keep all this documentation out of the branches where we do active development on the codebase.

**Pull request merged**
